# Generated by Django 4.0.2 on 2022-03-27 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_gallery_alter_news_image_galleryfilter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='contributors/')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('website', models.URLField(max_length=300)),
                ('twitter', models.URLField(max_length=300)),
                ('github', models.URLField(max_length=300)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='galleryfilter',
            name='filter',
        ),
    ]
