# Generated by Django 4.0.3 on 2022-04-08 06:21

from django.db import migrations, models
import django.db.models.deletion
import django_tuieditor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournoi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'required': 'Veuillez entrer votre nom et prénom.'}, max_length=150)),
                ('email', models.EmailField(blank=True, error_messages={'required': 'Veuillez entrer votre adresse email.'}, max_length=254, null=True)),
                ('phone', models.CharField(error_messages={'required': 'Veuillez entrer votre numéro de téléphone.'}, max_length=9)),
                ('subject', models.CharField(error_messages={'required': 'Veuillez entrer le titre de votre message.'}, max_length=100)),
                ('message', models.TextField(error_messages={'required': 'Veuillez entrer votre message.'})),
            ],
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='contributors/')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('website', models.URLField(max_length=300)),
                ('twitter', models.URLField(max_length=300)),
                ('github', models.URLField(max_length=300)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('edition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='tournoi.edition')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='news_placeholder.jpg', upload_to='actualites/')),
                ('title', models.CharField(max_length=200)),
                ('description', django_tuieditor.models.MarkdownField(max_length=150)),
                ('add_on', models.DateField(auto_now=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournoi.edition')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='galleries/')),
                ('alt', models.CharField(blank=True, max_length=20, null=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.gallery')),
            ],
        ),
    ]
