# Generated by Django 4.0.2 on 2022-03-28 14:34

from django.db import migrations, models
import django.db.models.deletion
import django_tuieditor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'required': 'Veuillez entrer votre nom et prénom.'}, max_length=150)),
                ('email', models.EmailField(blank=True, error_messages={'required': 'Veuillez entrer votre adresse email.'}, max_length=254, null=True)),
                ('phone', models.CharField(error_messages={'required': 'Veuillez entrer votre numéro de téléphone.'}, max_length=9)),
                ('subject', models.CharField(error_messages={'required': 'Veuillez entrer le titre de votre message.'}, max_length=100)),
                ('message', models.TextField(error_messages={'required': 'Veuillez entrer votre message.'})),
            ],
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='contributors/')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('website', models.URLField(max_length=300)),
                ('twitter', models.URLField(max_length=300)),
                ('github', models.URLField(max_length=300)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('begin_date', models.DateField(default=None, null=True)),
                ('end_date', models.DateField(default=None, null=True)),
                ('status', models.CharField(choices=[('programmed', 'programmed'), ('active', 'active')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='core.edition')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(blank=True, max_length=50, null=True)),
                ('matricule', models.CharField(blank=True, default='00000', max_length=20, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='players/photos')),
                ('add_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Poule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('add_date', models.DateField(auto_now_add=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poules', to='core.edition')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('abreviation', models.CharField(default='team', max_length=50)),
                ('add_date', models.DateField(auto_now_add=True)),
                ('logo', models.ImageField(default='default.png', upload_to='team/logos/')),
            ],
        ),
        migrations.CreateModel(
            name='PouleTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.SmallIntegerField(default=0)),
                ('points', models.SmallIntegerField(default=0)),
                ('conceded_goals', models.SmallIntegerField(default=0)),
                ('goals_average', models.SmallIntegerField(default=0)),
                ('poule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.poule')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='news_placeholder.jpg', upload_to='actualites/')),
                ('title', models.CharField(max_length=50)),
                ('description', django_tuieditor.models.MarkdownField(max_length=150)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.edition')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateField(auto_now_add=True)),
                ('date_to_play', models.DateTimeField(null=True)),
                ('state', models.CharField(choices=[('reporte', 'Reported'), ('en cours', 'Current'), ('annulé', 'Cancel'), ('terminé', 'Finish'), ('a programmé', 'To Program')], default='a programmé', max_length=50)),
                ('match_type', models.CharField(choices=[('FINAL', 'Final'), ('SEMIFINAL', 'Semifinal'), ('POULE', 'Poule'), ('AMICAL', 'Amical')], default='POULE', max_length=50)),
                ('goal_team1', models.SmallIntegerField(default=0)),
                ('goal_team2', models.SmallIntegerField(default=0)),
                ('title', models.CharField(default=None, max_length=50, null=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.edition')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='core.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='core.team')),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('CSC', 'Csc'), ('SP', 'Sp'), ('N', 'N')], max_length=50)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='goals', to='core.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='goals', to='core.player')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='galleries/')),
                ('alt', models.CharField(blank=True, max_length=20, null=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.gallery')),
            ],
        ),
    ]
