# Generated by Django 4.0.3 on 2022-03-29 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournoi', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='match',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='player',
        ),
        migrations.RemoveField(
            model_name='match',
            name='edition',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team2',
        ),
        migrations.RemoveField(
            model_name='poule',
            name='edition',
        ),
        migrations.RemoveField(
            model_name='pouleteam',
            name='poule',
        ),
        migrations.RemoveField(
            model_name='pouleteam',
            name='team',
        ),
        migrations.AlterField(
            model_name='gallery',
            name='edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='tournoi.edition'),
        ),
        migrations.AlterField(
            model_name='news',
            name='edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournoi.edition'),
        ),
        migrations.DeleteModel(
            name='Edition',
        ),
        migrations.DeleteModel(
            name='Goal',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='Poule',
        ),
        migrations.DeleteModel(
            name='PouleTeam',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
