# Generated by Django 4.0.3 on 2022-04-08 14:37

from django.db import migrations, models
import django.db.models.deletion
import django_tuieditor.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, default='author/avatar.png', null=True, upload_to='author')),
                ('description', django_tuieditor.models.MarkdownField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=django_tuieditor.models.MarkdownField(),
        ),
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.author'),
            preserve_default=False,
        ),
    ]
