# Generated by Django 3.2 on 2022-04-08 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_author_alter_news_description'),
        ('core', '0002_author_alter_news_description_news_author'),
    ]

    operations = [
    ]
