# Generated by Django 4.0.3 on 2022-03-29 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournoi', '0001_initial'),
        ('core', '0002_remove_goal_match_remove_goal_player_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='edition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='tournoi.edition'),
        ),
    ]
