# Generated by Django 4.0.3 on 2022-03-30 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_gallery_edition'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='add_on',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
