# Generated by Django 4.0.2 on 2022-03-24 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contactinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='email',
            field=models.EmailField(blank=True, error_messages={'required': 'Veuillez entrer votre adresse email.'}, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='message',
            field=models.TextField(error_messages={'required': 'Veuillez entrer votre message.'}),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='name',
            field=models.CharField(error_messages={'required': 'Veuillez entrer votre nom et prénom.'}, max_length=150),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone',
            field=models.CharField(error_messages={'required': 'Veuillez entrer votre numéro de téléphone.'}, max_length=9),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='subject',
            field=models.CharField(error_messages={'required': 'Veuillez entrer le titre de votre message.'}, max_length=100),
        ),
    ]
