# Generated by Django 4.0.3 on 2022-04-04 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_news_title'),
        ('core', '0004_news_add_on_alter_news_title'),
    ]

    operations = [
    ]
