# Generated by Django 4.0.3 on 2022-03-27 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_gallery_alter_news_image_galleryfilter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryfilter',
            name='filter',
        ),
    ]
