# Generated by Django 4.0.3 on 2022-03-27 04:37

from django.db import migrations, models
import django.db.models.deletion
import django_tuieditor.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_galleryfilter_filter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GalleryFilter',
        ),
        migrations.AddField(
            model_name='gallery',
            name='edition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.edition'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='edition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.edition'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='galleries/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=django_tuieditor.models.MarkdownField(max_length=150),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(default='news_placeholder.jpg', upload_to='actualites/'),
        ),
    ]
