# Generated by Django 4.0.3 on 2022-03-27 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_galleryfilter_gallery_edition_news_edition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edition',
            name='active',
        ),
        migrations.RemoveField(
            model_name='edition',
            name='programmed',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='alt',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='image',
        ),
        migrations.RemoveField(
            model_name='match',
            name='winner',
        ),
        migrations.AddField(
            model_name='edition',
            name='status',
            field=models.CharField(choices=[('programmed', 'programmed'), ('active', 'active')], default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gallery',
            name='edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='core.edition'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='goals', to='core.match'),
        ),
        migrations.AlterField(
            model_name='match',
            name='date_to_play',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='galleries/')),
                ('alt', models.CharField(blank=True, max_length=20, null=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.gallery')),
            ],
        ),
    ]
