# Generated by Django 3.2 on 2022-04-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournoi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='dossard',
            field=models.IntegerField(default=1),
        ),
    ]
