# Generated by Django 4.0.3 on 2022-04-02 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournoi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pouleteam',
            old_name='conceded_goals',
            new_name='defeat',
        ),
        migrations.RenameField(
            model_name='pouleteam',
            old_name='goals',
            new_name='null',
        ),
        migrations.RenameField(
            model_name='pouleteam',
            old_name='goals_average',
            new_name='victory',
        ),
    ]
