# Generated by Django 4.0.3 on 2022-04-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournoi', '0002_rename_conceded_goals_pouleteam_defeat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='stade_name',
            field=models.CharField(default='Stade Mateco', max_length=200),
        ),
    ]
