# Generated by Django 4.0.3 on 2022-04-04 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournoi', '0003_match_stade_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='edition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='tournoi.edition'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='top_player',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='nb_players',
            field=models.IntegerField(default=11),
        ),
    ]
