# Generated by Django 4.0.3 on 2022-04-04 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournoi', '0004_player_edition_player_top_player_team_nb_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='pouleteam',
            name='red_cart',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pouleteam',
            name='yellow_cart',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pouleteam',
            name='poule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poule_teams', to='tournoi.poule'),
        ),
        migrations.AlterField(
            model_name='pouleteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poule_team', to='tournoi.team'),
        ),
    ]
